"use client";
import {FormEvent,useMemo,useState} from "react";
import { Toaster, createToaster } from "@chakra-ui/react";
const toaster=createToaster({placement:"top-end",pauseOnPageIdle:true});
const TYPES=[["STORY","Story / article"],["PERSON","Person"],["BUSINESS","Business"],["PLACE","Place"],["EVENT","Event"],["NEWS","News / announcement"],["PHOTO_STORY","Photo story"],["VIDEO","Video"],["PRODUCT_LAUNCH","Product / launch"],["COMMUNITY_STORY","Community story"],["OTHER","Something else"]];
const CITIES=[
["Lagos","Nigeria",true],["Johannesburg","South Africa",true],["Cape Town","South Africa",false],["Abuja","Nigeria",false],["Accra","Ghana",false],["Nairobi","Kenya",false],["Durban","South Africa",false],["Pretoria","South Africa",false],["Port Harcourt","Nigeria",false],["Ibadan","Nigeria",false],["Kano","Nigeria",false],["Kigali","Rwanda",false],["Addis Ababa","Ethiopia",false],["Dar es Salaam","Tanzania",false],["Kampala","Uganda",false],["Cairo","Egypt",false],["Casablanca","Morocco",false],["Dakar","Senegal",false],["London","United Kingdom",false],["Paris","France",false],["Berlin","Germany",false],["Amsterdam","Netherlands",false],["Madrid","Spain",false],["Barcelona","Spain",false],["Lisbon","Portugal",false],["Rome","Italy",false],["Milan","Italy",false],["New York","United States",false],["Los Angeles","United States",false],["Chicago","United States",false],["Miami","United States",false],["Toronto","Canada",false],["Vancouver","Canada",false],["Mexico City","Mexico",false],["São Paulo","Brazil",false],["Rio de Janeiro","Brazil",false],["Buenos Aires","Argentina",false],["Dubai","United Arab Emirates",false],["Abu Dhabi","United Arab Emirates",false],["Doha","Qatar",false],["Mumbai","India",false],["Delhi","India",false],["Bengaluru","India",false],["Singapore","Singapore",false],["Bangkok","Thailand",false],["Tokyo","Japan",false],["Seoul","South Korea",false],["Hong Kong","Hong Kong",false],["Sydney","Australia",false],["Melbourne","Australia",false]
] as const;
const WHO=[["INDIVIDUAL","Individual"],["BUSINESS","Business"],["BRAND","Brand"],["CREATOR","Creator"],["JOURNALIST","Journalist"],["PR_AGENCY","PR / agency"],["MEDIA_ORGANISATION","Media organisation"],["NONPROFIT","Nonprofit"],["GOVERNMENT_INSTITUTION","Government / institution"],["OTHER","Other"]];
export function ContributionForm(){const [step,setStep]=useState(1);const [cityOpen,setCityOpen]=useState(false);const [cityQuery,setCityQuery]=useState("");const [busy,setBusy]=useState(false);const [done,setDone]=useState(false);const [data,setData]=useState({city:"",submissionType:"STORY",contributorType:"INDIVIDUAL",title:"",summary:"",story:"",links:"",contactName:"",contactEmail:"",socialProfiles:"",desiredIssue:"November 2026"});
const cityMatches=useMemo(()=>{const q=cityQuery.trim().toLowerCase();return CITIES.filter(([city,country])=>!q||city.toLowerCase().includes(q)||country.toLowerCase().includes(q)).slice(0,10)},[cityQuery]);
function set(k:string,v:string){setData(x=>({...x,[k]:v}))}
function chooseCity(city:string){set("city",city);setCityQuery(city);setCityOpen(false)}function friendlyError(payload:any,status:number){const raw=typeof payload?.error==="string"?payload.error:"";if(raw.includes('"summary"')||raw.includes("summary")&&raw.includes("20"))return "Please tell us a little more about the story. Your pitch should be at least 20 characters.";if(raw.toLowerCase().includes("email"))return "Please enter a valid email address so our editors can reach you.";if(status>=500)return "We could not send your story right now. Please try again in a moment.";return "Please check the information you entered and try again."}
async function submit(e:FormEvent){e.preventDefault();if(data.summary.trim().length<20){setStep(3);toaster.create({title:"Tell us a little more",description:"Your pitch should be at least 20 characters so our editors understand the story.",type:"error",duration:5000});return}setBusy(true);try{const r=await fetch("/api/submissions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(data)});let p:any={};try{p=await r.json()}catch{}if(!r.ok){toaster.create({title:"We couldn't submit this yet",description:friendlyError(p,r.status),type:"error",duration:6000});return}setDone(true);toaster.create({title:"Story submitted",description:"Your contribution is now with the XpoMag editorial team.",type:"success",duration:4500})}catch{toaster.create({title:"Connection problem",description:"We couldn't reach XpoMag. Check your connection and try again.",type:"error",duration:6000})}finally{setBusy(false)}}
if(done)return <><Toaster toaster={toaster}/><div className="xp-contribute__success"><span>SUBMISSION RECEIVED</span><h2>Thank you.<br/>The editors have it.</h2><p>Submission does not guarantee publication. If the story is a fit, XpoMag may contact you for more information, interviews or assets.</p><a href="/">Back to XpoMag →</a></div></>;
return <><Toaster toaster={toaster}/><form className="xp-contribute__form" onSubmit={submit}><div className="xp-contribute__progress"><span>SUBMIT TO XPOMAG</span><span>0{step} / 04</span></div>
{step===1?<section><span className="xp-contribute__number">01</span><h2>Where is this story?</h2><p>Choose the city this belongs to. You can also suggest a city XpoMag does not publish yet.</p><label className="xp-contribute__city-label">City<div className="xp-city-picker"><input required autoFocus autoComplete="off" role="combobox" aria-expanded={cityOpen} value={cityQuery} onFocus={()=>setCityOpen(true)} onChange={e=>{setCityQuery(e.target.value);set("city","");setCityOpen(true)}} placeholder="Search cities worldwide..."/>{cityOpen?<div className="xp-city-picker__menu" role="listbox">{cityMatches.length?cityMatches.map(([city,country,live])=><button type="button" role="option" aria-selected={data.city===city} key={city} onMouseDown={e=>e.preventDefault()} onClick={()=>chooseCity(city)}><span><strong>{city}</strong><small>{country}</small></span>{live?<b>LIVE ON XPOMAG</b>:<em>COMING SOON</em>}</button>):<p>No matching city yet. Try another city name.</p>}</div>:null}</div></label><label>Preferred issue<input value={data.desiredIssue} onChange={e=>set("desiredIssue",e.target.value)} placeholder="e.g. November 2026"/></label></section>:null}
{step===2?<section><span className="xp-contribute__number">02</span><h2>What are you sending us?</h2><div className="xp-contribute__choices">{TYPES.map(([v,l])=><button type="button" className={data.submissionType===v?"is-selected":""} onClick={()=>set("submissionType",v)} key={v}>{l}</button>)}</div><h3>Who are you?</h3><div className="xp-contribute__choices">{WHO.map(([v,l])=><button type="button" className={data.contributorType===v?"is-selected":""} onClick={()=>set("contributorType",v)} key={v}>{l}</button>)}</div></section>:null}
{step===3?<section><span className="xp-contribute__number">03</span><h2>Tell us the story.</h2><p>You do not need a finished magazine article. A strong lead is enough.</p><label>Working title<input required value={data.title} onChange={e=>set("title",e.target.value)} placeholder="What should we know about?"/></label><label>Pitch / summary<textarea required minLength={20} value={data.summary} onChange={e=>set("summary",e.target.value)} placeholder="Why is this interesting, timely or useful to people in the city?"/></label><label>Full story or supporting information <em>Optional</em><textarea value={data.story} onChange={e=>set("story",e.target.value)} placeholder="Add context, names, dates, quotes or anything that helps us investigate."/></label><label>Relevant links <em>Optional</em><textarea value={data.links} onChange={e=>set("links",e.target.value)} placeholder="Website, article, Drive/Dropbox media folder, video links..."/></label></section>:null}
{step===4?<section><span className="xp-contribute__number">04</span><h2>How can we reach you?</h2><label>Your name<input required value={data.contactName} onChange={e=>set("contactName",e.target.value)}/></label><label>Email<input required type="email" value={data.contactEmail} onChange={e=>set("contactEmail",e.target.value)}/></label><label>Social profiles <em>Optional</em><input value={data.socialProfiles} onChange={e=>set("socialProfiles",e.target.value)} placeholder="@handle or profile links"/></label><div className="xp-contribute__notice"><strong>Open contribution. Curated publication.</strong><p>Submitting is free and does not guarantee editorial coverage. Sponsored stories and advertising are separate, clearly labelled products.</p></div></section>:null}
<div className="xp-contribute__actions">{step>1?<button type="button" onClick={()=>setStep(x=>x-1)}>← Back</button>:<a href="/">Cancel</a>}{step<4?<button type="button" onClick={()=>setStep(x=>x+1)}>Continue →</button>:<button type="submit" disabled={busy}>{busy?"Sending...":"Submit to XpoMag →"}</button>}</div></form></>}
