"use client";
import {FormEvent,useState} from "react";
const TYPES=[["STORY","Story / article"],["PERSON","Person"],["BUSINESS","Business"],["PLACE","Place"],["EVENT","Event"],["NEWS","News / announcement"],["PHOTO_STORY","Photo story"],["VIDEO","Video"],["PRODUCT_LAUNCH","Product / launch"],["COMMUNITY_STORY","Community story"],["OTHER","Something else"]];
const WHO=[["INDIVIDUAL","Individual"],["BUSINESS","Business"],["BRAND","Brand"],["CREATOR","Creator"],["JOURNALIST","Journalist"],["PR_AGENCY","PR / agency"],["MEDIA_ORGANISATION","Media organisation"],["NONPROFIT","Nonprofit"],["GOVERNMENT_INSTITUTION","Government / institution"],["OTHER","Other"]];
export function ContributionForm(){const [step,setStep]=useState(1);const [busy,setBusy]=useState(false);const [done,setDone]=useState(false);const [error,setError]=useState("");const [data,setData]=useState({city:"",submissionType:"STORY",contributorType:"INDIVIDUAL",title:"",summary:"",story:"",links:"",contactName:"",contactEmail:"",socialProfiles:"",desiredIssue:"November 2026"});
function set(k:string,v:string){setData(x=>({...x,[k]:v}))}async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{const r=await fetch("/api/submissions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(data)});const p=await r.json();if(!r.ok)throw new Error(p.error??"Could not submit your story");setDone(true)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
if(done)return <div className="xp-contribute__success"><span>SUBMISSION RECEIVED</span><h2>Thank you.<br/>The editors have it.</h2><p>Submission does not guarantee publication. If the story is a fit, XpoMag may contact you for more information, interviews or assets.</p><a href="/">Back to XpoMag →</a></div>;
return <form className="xp-contribute__form" onSubmit={submit}><div className="xp-contribute__progress"><span>SUBMIT TO XPOMAG</span><span>0{step} / 04</span></div>
{step===1?<section><span className="xp-contribute__number">01</span><h2>Where is this story?</h2><p>Choose the city this belongs to. You can also suggest a city XpoMag does not publish yet.</p><label>City<input required autoFocus value={data.city} onChange={e=>set("city",e.target.value)} placeholder="e.g. Lagos, Johannesburg, Cape Town"/></label><label>Preferred issue<input value={data.desiredIssue} onChange={e=>set("desiredIssue",e.target.value)} placeholder="e.g. November 2026"/></label></section>:null}
{step===2?<section><span className="xp-contribute__number">02</span><h2>What are you sending us?</h2><div className="xp-contribute__choices">{TYPES.map(([v,l])=><button type="button" className={data.submissionType===v?"is-selected":""} onClick={()=>set("submissionType",v)} key={v}>{l}</button>)}</div><h3>Who are you?</h3><div className="xp-contribute__choices">{WHO.map(([v,l])=><button type="button" className={data.contributorType===v?"is-selected":""} onClick={()=>set("contributorType",v)} key={v}>{l}</button>)}</div></section>:null}
{step===3?<section><span className="xp-contribute__number">03</span><h2>Tell us the story.</h2><p>You do not need a finished magazine article. A strong lead is enough.</p><label>Working title<input required value={data.title} onChange={e=>set("title",e.target.value)} placeholder="What should we know about?"/></label><label>Pitch / summary<textarea required minLength={20} value={data.summary} onChange={e=>set("summary",e.target.value)} placeholder="Why is this interesting, timely or useful to people in the city?"/></label><label>Full story or supporting information <em>Optional</em><textarea value={data.story} onChange={e=>set("story",e.target.value)} placeholder="Add context, names, dates, quotes or anything that helps us investigate."/></label><label>Relevant links <em>Optional</em><textarea value={data.links} onChange={e=>set("links",e.target.value)} placeholder="Website, article, Drive/Dropbox media folder, video links..."/></label></section>:null}
{step===4?<section><span className="xp-contribute__number">04</span><h2>How can we reach you?</h2><label>Your name<input required value={data.contactName} onChange={e=>set("contactName",e.target.value)}/></label><label>Email<input required type="email" value={data.contactEmail} onChange={e=>set("contactEmail",e.target.value)}/></label><label>Social profiles <em>Optional</em><input value={data.socialProfiles} onChange={e=>set("socialProfiles",e.target.value)} placeholder="@handle or profile links"/></label><div className="xp-contribute__notice"><strong>Open contribution. Curated publication.</strong><p>Submitting is free and does not guarantee editorial coverage. Sponsored stories and advertising are separate, clearly labelled products.</p></div>{error?<p className="xp-contribute__error">{error}</p>:null}</section>:null}
<div className="xp-contribute__actions">{step>1?<button type="button" onClick={()=>setStep(x=>x-1)}>← Back</button>:<a href="/">Cancel</a>}{step<4?<button type="button" onClick={()=>setStep(x=>x+1)}>Continue →</button>:<button type="submit" disabled={busy}>{busy?"Sending...":"Submit to XpoMag →"}</button>}</div></form>}
