"use client";
import {useMemo,useState} from "react";
type S={id:string;city:string;submissionType:string;contributorType:string;title:string;summary:string;story?:string|null;links?:string|null;contactName:string;contactEmail:string;desiredIssue:string|null;status:string;editorNotes:string|null;assignedIssue?:string|null;neighbourhood?:string|null;category?:string|null;aiSummary?:string|null;aiMissingInfo?:string[];createdAt:string};
const STATUSES=["INCOMING","REVIEWING","SHORTLISTED","RESEARCH","APPROVED","DESIGNING","SCHEDULED","PUBLISHED","REJECTED","ARCHIVED"];
const CATEGORIES=["Food","Beauty","Business","Design","Fashion","Property","Culture","Nightlife","Tech","Events","People","Community"];
function assist(x:S){const text=[x.title,x.summary,x.story].filter(Boolean).join(" ");const missing:string[]=[];if(!x.story||x.story.trim().length<120)missing.push("More supporting detail");if(!x.links)missing.push("Source or supporting links");if(!/\b(19|20)\d{2}\b/.test(text))missing.push("Dates / timing");if(!x.neighbourhood)missing.push("Neighbourhood");return{aiSummary:x.summary.length>260?x.summary.slice(0,257)+"...":x.summary,aiMissingInfo:missing}}
export function EditorialQueue({initial}:{initial:S[]}){const [items,setItems]=useState(initial);const [filter,setFilter]=useState("ALL");const [city,setCity]=useState("ALL");const [selected,setSelected]=useState<S|null>(null);const cities=useMemo(()=>["ALL",...Array.from(new Set(items.map(x=>x.city)))],[items]);const shown=useMemo(()=>items.filter(x=>(filter==="ALL"||x.status===filter)&&(city==="ALL"||x.city===city)),[items,filter,city]);
async function createStory(item:S){if(item.status!=="APPROVED"){return}const publicationSlug=item.city.toLowerCase()==="johannesburg"?"joburg":item.city.toLowerCase().replace(/[^a-z0-9]+/g,"-");const issueLabel=item.assignedIssue??item.desiredIssue;if(!issueLabel)return;const r=await fetch(`/api/admin-submissions/${item.id}/story`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({publicationSlug,issueLabel,kind:"EDITORIAL"})});if(r.ok){location.href="/stories"}}
async function patch(item:S,input:Partial<S>){const r=await fetch(`/api/admin-submissions/${item.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(input)});if(r.ok){const p=await r.json();setItems(xs=>xs.map(x=>x.id===item.id?p.submission:x));setSelected(p.submission)}}
return <main className="xp-editorial"><header><div><p>EDITORIAL CURATION</p><h1>Find the stories<br/>worth opening.</h1></div><div className="xp-editorial__stats"><b>{items.length}</b><span>submissions</span><b>{items.filter(x=>x.status==="SHORTLISTED").length}</b><span>shortlisted</span></div></header>
<div className="xp-editorial__toolbar"><div>{["ALL",...STATUSES].map(x=><button key={x} className={filter===x?"is-active":""} onClick={()=>setFilter(x)}>{x.replace("_"," ")}</button>)}</div><select value={city} onChange={e=>setCity(e.target.value)}>{cities.map(x=><option key={x}>{x}</option>)}</select></div>
<div className="xp-editorial__layout"><section className="xp-editorial__list">{shown.length?shown.map(x=><button className={"xp-editorial__card "+(selected?.id===x.id?"is-selected":"")} key={x.id} onClick={()=>setSelected(x)}><div><span>{x.city} · {x.submissionType.replace("_"," ")}</span><b>{x.title}</b><p>{x.summary}</p><small>{x.contactName}{x.desiredIssue?` · prefers ${x.desiredIssue}`:""}</small></div><em>{x.status}</em></button>):<div className="xp-editorial__empty">No submissions in this view.</div>}</section>
<aside className="xp-editorial__detail">{selected?<><span>SUBMISSION / {selected.city.toUpperCase()}</span><h2>{selected.title}</h2><p>{selected.summary}</p><div className="xp-editorial__fields"><label>Status<select value={selected.status} onChange={e=>patch(selected,{status:e.target.value})}>{STATUSES.map(s=><option key={s}>{s}</option>)}</select></label><label>Assign to issue<input value={selected.assignedIssue??selected.desiredIssue??""} placeholder="e.g. November 2026" onChange={e=>setSelected({...selected,assignedIssue:e.target.value})} onBlur={e=>patch(selected,{assignedIssue:e.target.value})}/></label><label>Neighbourhood<input value={selected.neighbourhood??""} placeholder="e.g. Lekki, VI, Sandton" onChange={e=>setSelected({...selected,neighbourhood:e.target.value})} onBlur={e=>patch(selected,{neighbourhood:e.target.value})}/></label><label>Category<select value={selected.category??""} onChange={e=>patch(selected,{category:e.target.value})}><option value="">Choose category</option>{CATEGORIES.map(c=><option key={c}>{c}</option>)}</select></label><label>Editorial notes<textarea value={selected.editorNotes??""} placeholder="Internal notes, interview needs, angle..." onChange={e=>setSelected({...selected,editorNotes:e.target.value})} onBlur={e=>patch(selected,{editorNotes:e.target.value})}/></label></div>{selected.status==="APPROVED"?<div className="xp-editorial__promote"><b>Ready to become a story?</b><p>This creates an editable story draft while preserving the original source record.</p><button disabled={!(selected.assignedIssue??selected.desiredIssue)} onClick={()=>createStory(selected)}>Create story draft →</button></div>:null}<div className="xp-editorial__ai"><div><b>Editorial assistant</b><small>Assistive only — editor decides what gets published.</small></div><button onClick={()=>patch(selected,assist(selected))}>Analyse submission</button>{selected.aiSummary?<p><strong>Summary</strong>{selected.aiSummary}</p>:null}{selected.aiMissingInfo?.length?<p><strong>Missing / verify</strong>{selected.aiMissingInfo.join(" · ")}</p>:null}</div></>:<div className="xp-editorial__empty">Select a submission to review, assign and curate it.</div>}</aside></div></main>}
