"use client";
import { FormEvent, useEffect, useState } from "react";
type Publication={id:string;name:string;slug:string;city:string|null;country:string|null;status:string;followerCount:number;featured:boolean};
const empty={name:"",slug:"",type:"CITY",city:"",country:"",countryCode:"",description:"",tagline:"Every city has a story.",status:"DRAFT",launchDate:"",featured:false};
export function PublicationAdmin(){
 const [items,setItems]=useState<Publication[]>([]),[form,setForm]=useState<any>(empty),[message,setMessage]=useState("");
 async function load(){const r=await fetch("/api/publications?admin=1",{cache:"no-store"});if(r.ok)setItems((await r.json()).publications??[])}
 useEffect(()=>{load()},[]);
 async function submit(e:FormEvent){e.preventDefault();setMessage("Saving…");const payload={...form,city:form.city||null,country:form.country||null,countryCode:form.countryCode||null,description:form.description||null,tagline:form.tagline||null,launchDate:form.launchDate||null};const r=await fetch("/api/publications",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});if(!r.ok){setMessage("Could not save publication");return}setMessage("Saved");setForm(empty);await load()}
 return <main className="xp-pub-admin"><header><div><a href="/">← Admin</a><p>PUBLICATIONS</p><h1>Manage the XpoMag network.</h1></div><a href="http://localhost:3000/explore" target="_blank">Open Explore ↗</a></header>
 <section className="xp-pub-admin__grid"><div><h2>Publications</h2>{items.map(p=><article key={p.id}><div><strong>{p.name}</strong><span>{p.city}, {p.country}</span></div><div><b>{p.status.replace("_"," ")}</b><small>{p.followerCount} followers</small></div></article>)}</div>
 <form onSubmit={submit}><h2>Add or update</h2><label>Name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Slug<input required pattern="[a-z0-9-]+" value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})}/></label><div className="xp-pub-admin__row"><label>City<input value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></label><label>Country<input value={form.country} onChange={e=>setForm({...form,country:e.target.value})}/></label></div><label>Tagline<input value={form.tagline} onChange={e=>setForm({...form,tagline:e.target.value})}/></label><label>Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="xp-pub-admin__row"><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>DRAFT</option><option>COMING_SOON</option><option>ACTIVE</option><option>ARCHIVED</option></select></label><label>Launch date<input type="date" value={form.launchDate} onChange={e=>setForm({...form,launchDate:e.target.value})}/></label></div><label className="xp-pub-admin__check"><input type="checkbox" checked={form.featured} onChange={e=>setForm({...form,featured:e.target.checked})}/> Featured publication</label><button>Save publication</button><p>{message}</p></form></section></main>
}
